fix bad browser name raising AttributeError
fix for bad browser name raising AttributeError: 'Selenium2Library'
object has no attribute 'fireox' instead of ValueError: fireox is not a
supported browser.
PEP8 near code change and some housekeeping